---
- name: Copy storage.yaml to master node
  run_once: true
  template:
    src: storage.yaml.j2
    dest: "/tmp/storage.yaml"

- name: Apply storage.yaml
  run_once: true
  become: yes
  shell: kubectl apply -f /tmp/storage.yaml
  retries: 10
  delay: 5
  register: result
  until: result.rc == 0

- name: Clean storage.yaml file
  run_once: true
  file:
    state: absent
    path: "/tmp/storage.yaml"

- name: Make all storage classes non default
  run_once: true
  become: yes
  shell: 'kubectl get sc --template ''{% raw %}{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}{% endraw %}'' | xargs kubectl patch storageclass -p ''{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'''
  retries: 10
  delay: 5
  register: result
  until: result.rc == 0

# - name: Make storage class default
#   run_once: true
#   become: yes
#   shell: 'kubectl patch storageclass nfs -p ''{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'''
#   retries: 10
#   delay: 5
#   register: result
#   until: result.rc == 0
