---
- name: Add host to group 'nodes'
  add_host:
    name: "{{ item }}"
    groups: nodes
  with_items: "{{ nodes }}"

- name: Remove password from the key
  shell: ssh-keygen -p -P '{{ ssh_user_private_key_password }}' -N '' -f {{ ansible_ssh_private_key_file }}