apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: daiteap-clusterissuer
  namespace: daiteap-ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: daiteap-clusterissuer
    solvers:
    - http01:
        ingress:
          class: nginx