# Generated by Django 3.0.3 on 2022-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supports_multiple_installs',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
