# Generated by Django 3.0.3 on 2022-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='sync_ssh_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='sync_ssh_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ssh_synchronized_machines',
            field=models.ManyToManyField(blank=True, to='cloudcluster.Machine'),
        ),
    ]
