# Generated by Django 3.0.3 on 2022-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0002_service_supports_multiple_installs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='cloud_account_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
