# Generated by Django 3.0.3 on 2023-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0003_cloudaccount_cloud_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='longhorn_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='clusters',
            name='longhorn_password',
            field=models.TextField(default='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusters',
            name='longhorn_username',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]