# Generated by Django 3.0.3 on 2023-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0004_auto_20230120_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='contact',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
