# Generated by Django 3.0.3 on 2023-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcluster', '0005_auto_20230216_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='storage_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]