---
- name: Include ubuntu
  include: test_server/tasks/ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'

- name: Include debian
  include: test_server/tasks/debian.yaml
  when: ansible_distribution == 'Debian'
