- name: Add hosts and vars
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts_and_vars

- name: Add kubernetes role to user
  become: yes
  hosts: dc-node
  any_errors_fatal: true
  roles:
    - role: add_role
