- name: Add hosts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts

- name: Delete user
  hosts: nodes
  become: true
  any_errors_fatal: true
  roles:
    - role: delete_user