- name: Add hosts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts

- name: Add storage config
  hosts: azurenodes
  any_errors_fatal: true
  roles:
    - role: add_config

- name: Integrate storage
  hosts: masternode
  any_errors_fatal: true
  roles:
    - role: storage