---
- name: Add hosts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/raspberrypi

- hosts: master
  any_errors_fatal: true
  become: yes
  roles:
    - { role: k3s/get-token }

- hosts: node
  any_errors_fatal: true
  become: yes
  roles:
    - { role: k3s/node }
