apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    component: proxy
spec:
  selector:
    app: database
  ports:
    - name: http
      port: 3306
      protocol: TCP
  type: "{{ .Values.service.type }}"