# permissions for end users to view cloudinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: daiteap-operator
    app.kubernetes.io/part-of: daiteap-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudinstance-viewer-role
rules:
- apiGroups:
  - daiteap.com.daiteap.com
  resources:
  - cloudinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - daiteap.com.daiteap.com
  resources:
  - cloudinstances/status
  verbs:
  - get
