# permissions for end users to view kubernetesclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubernetescluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: daiteap-operator
    app.kubernetes.io/part-of: daiteap-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubernetescluster-viewer-role
rules:
- apiGroups:
  - cluster.daiteap.com
  resources:
  - kubernetesclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.daiteap.com
  resources:
  - kubernetesclusters/status
  verbs:
  - get
