FROM python:3.7
WORKDIR /cloudcluster

ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN apt-get install -y iproute2 ca-certificates gcc libffi-dev bash  git tk-dev tcl-dev

COPY cloudcluster/requirements.txt cloudcluster/requirements.txt
RUN pip install --upgrade pip
RUN pip3 install -r cloudcluster/requirements.txt

RUN wget https://storage.googleapis.com/kubernetes-release/release/v1.22.4/bin/linux/$(dpkg --print-architecture)/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

RUN wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_$(dpkg --print-architecture).zip -O terraform.zip
RUN wget https://get.helm.sh/helm-v3.3.4-linux-$(dpkg --print-architecture).tar.gz
RUN tar zxf helm-v3.3.4-linux-$(dpkg --print-architecture).tar.gz
RUN unzip terraform.zip
RUN mv ./linux-$(dpkg --print-architecture)/helm /usr/bin/
RUN mv terraform /usr/bin/
COPY .terraformrc /root/

RUN apt-get update &&  apt-get install -y tini npm openssl # wireguard
RUN npm install -g @terraform-visual/cli@0.2.1

RUN mkdir -p /root/.terraform.d/plugin-cache

ARG GIT_COMMIT_SHA=""
ENV GIT_SHA=$GIT_COMMIT_SHA

COPY . .

ENTRYPOINT ["tini", "--"]
CMD ["bash", "-c", "./test.sh && /usr/local/bin/celery -A cloudcluster worker -l info -O fair -c 3"]
