FROM python:3.7-slim
WORKDIR /cloudcluster

ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN apt-get install -y iproute2 ca-certificates gcc libffi-dev bash git tk-dev tcl-dev
RUN apt-get install -y tini wget unzip openssl
RUN apt-get install -y --no-install-recommends libmariadb-dev-compat

COPY cloudcluster/requirements.txt cloudcluster/requirements.txt
RUN pip install --upgrade pip
RUN pip3 install -r cloudcluster/requirements.txt

RUN wget https://storage.googleapis.com/kubernetes-release/release/v1.22.4/bin/linux/$(dpkg --print-architecture)/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

RUN wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_$(dpkg --print-architecture).zip -O terraform.zip
RUN wget https://get.helm.sh/helm-v3.12.3-linux-$(dpkg --print-architecture).tar.gz
RUN tar zxf helm-v3.12.3-linux-$(dpkg --print-architecture).tar.gz
RUN unzip terraform.zip
RUN rm -rf terraform.zip
RUN rm -rf helm-v3.12.3-linux-$(dpkg --print-architecture).tar.gz
RUN mv ./linux-$(dpkg --print-architecture)/helm /usr/bin/
RUN mv terraform /usr/bin/
COPY .terraformrc /root/

RUN mkdir -p /root/.terraform.d/plugin-cache

ARG GIT_COMMIT_SHA=""
ENV GIT_SHA=$GIT_COMMIT_SHA

COPY . .

ENTRYPOINT ["tini", "--"]
CMD ["bash", "-c", "./test.sh && /usr/local/bin/celery -A cloudcluster worker -l info -O fair -c 3"]
