- name: Lookup etcd member id
  shell: "{{ etcd_command }} member list | grep {{ node_name }} | cut -d, -f1"
  register: etcd_member_id
  ignore_errors: true
  changed_when: false
  check_mode: false

- debug:
    msg: "{{ etcd_command }} member list | grep {{ node_name }} | cut -d, -f1"

- debug:
    msg: "{{ etcd_member_id.stdout }}"

- debug:
    msg: "{{ etcd_member_id.stderr }}"

- name: Remove etcd member
  shell: "{{ etcd_command }} member remove {{ etcd_member_id.stdout }}"
  when: "etcd_member_id.rc == 0"
  ignore_errors: true
  changed_when: false
  check_mode: false