kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}"
data:
    AZURE_CLIENT_ID: "{{ .Values.azureClientId | b64enc  }}"
    AZURE_CLIENT_SECRET: "{{ .Values.azureClientSecret | b64enc  }}"
    DEFAULT_FROM_EMAIL: "{{ .Values.defaultFromEmail | b64enc  }}"
    DJANGO_SECRET_KEY: "{{ .Values.djangoSecretKey | b64enc  }}"
    EMAIL_HOST_USER: "{{ .Values.emailHostUser | b64enc  }}"
    EMAIL_API_KEY: "{{ .Values.emailApiKey | b64enc  }}"
    EMAIL_API_URL: "{{ .Values.emailApiUrl | b64enc  }}"
    EMAIL_HOST_PASSWORD: "{{ .Values.emailHostPassword | b64enc  }}"
    SERVER_EMAIL_ADDRESS: "{{ .Values.serverEmailAddress | b64enc  }}"
    VAULT_TOKEN: "{{ .Values.vaultToken | b64enc  }}"
type: Opaque