# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

jupyter:
  image:
    repository: tensorflow/tensorflow
    tag: 1.6.0-devel
    pullPolicy: IfNotPresent
  resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #  nvidia.com/gpu: 1
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  #  nvidia.com/gpu: 1
service:
  type: LoadBalancer
