---
drain_grace_period: 300
drain_timeout: 360s

etcd_command: kubectl exec etcd-{{ primary_master_node_name }} -n kube-system -- etcdctl --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/peer.crt --key /etc/kubernetes/pki/etcd/peer.key 