{{ if and (not .Values.wildcardTLS.secret) (and .Values.wildcardTLS.cert .Values.wildcardTLS.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress.wildcardTLSName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.wildcardTLS.cert }}
  tls.key: {{ .Values.wildcardTLS.key }}
{{- end }}
