{{ if not .Values.defaultTLS.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress.defaultTLSName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.defaultTLS.cert }}
  tls.key: {{ .Values.defaultTLS.key }}
{{- end }}
