apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- if .Values.config.annotations }}
  annotations:
{{ toYaml .Values.config.annotations | indent 4 }}
{{- end }}
data:
{{- if .Values.config.entries }}
{{ toYaml .Values.config.entries | indent 2 }}
{{- end }}
