---
- name: Add hosts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts

- name: Fix coredns
  hosts: master
  become: yes
  any_errors_fatal: true
  roles:
    - role: fix_coredns