---
- name: Add hosts and vars
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts_and_vars

- name: Apply the kerberos-server role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: kerberos-server

- name: Apply the kerberos-client role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: kerberos-client

- name: Apply the ldap-server role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: ldap-server

- name: Apply the sasl-auth role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: sasl-auth

- name: Apply the sssd-client role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: sssd-client

- name: Apply the ldap-client role to the domain-controller group
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: ldap-client

- name: Test
  hosts: domain-controller
  any_errors_fatal: true
  become: yes
  roles:
    - role: test-roles
