apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "jupyter-notebook.name" . }}
    chart: {{ template "jupyter-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: claim-{{ template "jupyter-notebook.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
