apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: daiteap
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: env
        value: production
      - name: auth.username
        value: guest
      - name: auth.password
        value: guest        
      valueFiles:
      - values.yaml
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.10.3
  syncPolicy:
    automated: {}
