apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: daiteap
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: '*'
    jqPathExpressions:
    - .webhooks
    kind: '*'
  project: default
  source:
    helm:
      parameters:
      - name: server.auditStorage.size
        value: 5Gi
      - name: server.dataStorage.size
        value: 5Gi
      - name: server.ha.config
        value: ui = true listener "tcp" {  tls_disable = 1  address = "[::]:8200"  cluster_address
          = "[::]:8201"}storage "consul" {  path = "vault"  address = "HOST_IP:8500"}service_registration
          "kubernetes" {}# Example configuration for using auto-unseal, using Google
          Cloud KMS. The# GKMS keys must already exist, and the cluster must have
          a service account# that is authorized to access GCP KMS.#seal "gcpckms"
          {#   project     = "vault-helm-dev-246514"#   region      = "global"#   key_ring    =
          "vault-helm-unseal-kr"#   crypto_key  = "vault-helm-unseal-key"#}
      - name: server.ha.raft.config
        value: ui = true listener "tcp" {  tls_disable = 1  address = "[::]:8200"  cluster_address
          = "[::]:8201"}storage "raft" {  path = "/vault/data"}service_registration
          "kubernetes" {}
      - name: server.standalone.config
        value: ui = true listener "tcp" {  tls_disable = 1  address = "[::]:8200"  cluster_address
          = "[::]:8201"}storage "mysql" {  address = "database:3306"  username =
          "daiteap"  password = "o4IgTPif2WR6dCXIhuNC"  database = "vault"  plaintext_connection_allowed
          = "true"}# Example configuration for using auto-unseal, using Google Cloud
          KMS. The# GKMS keys must already exist, and the cluster must have a service
          account# that is authorized to access GCP KMS.#seal "gcpckms" {#   project     =
          "vault-helm-dev"#   region      = "global"#   key_ring    = "vault-helm-unseal-kr"#   crypto_key  =
          "vault-helm-unseal-key"#}
      valueFiles:
      - values.yaml
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
  syncPolicy: {}
