---
- name: Get name of the default network interface
  shell: ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | head -n 1 | awk '{print $3;}'
  register: default_interface

- name: Update mtu
  template:
    src: 99-custom-mtu.yaml.j2
    dest: "/etc/netplan/99-custom-mtu.yaml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    force: yes

- name: Apply netplan changes
  shell: netplan apply

- name: Fail if mtu is not changed
  shell: cat /sys/class/net/{{ default_interface.stdout }}/mtu
  retries: 10
  delay: 10
  until: mtu == host_mtu.stdout
  register: host_mtu