---
- name: Update apt-get
  shell: "apt update"

- name: Install ca-certificates package
  yum:
    name: ca-certificates
    state: latest
  register: caresult
  retries: 10
  until: caresult is succeeded
  delay: 30

- name: Enable dynamic CA configuration feature
  shell: update-ca-certificates force-enable

- name: Check that the ca.crt exists
  stat:
    path: "{{ playbook_dir }}/ca.crt"
  register: stat_result

- name: Fetch ca.crt
  fetch:
    src: "/root/easy-rsa-3.0.1/easyrsa3/pki/ca.crt"
    dest: "{{ playbook_dir }}/ca.crt"
    flat: yes
  when: stat_result.stat.exists == False and ansible_hostname == hostvars[groups['CA_scm_server'][0]]

- name: Copy ca.crt to /etc/pki/ca-trust/source/anchors/ca.crt
  copy:
    src: "{{ playbook_dir }}/ca.crt"
    dest: /usr/local/share/ca-certificates/ca.crt
    owner: root
    group: root
    mode: 0755

- name: Update system ca-certificates
  shell: update-ca-certificates extract
