---
- name: Add hosts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: add_hosts

- name: Install prometheus-operations
  hosts: master
  become: yes
  any_errors_fatal: true
  roles:
    - role: helm-prometheus-operations