apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-{{ .Release.Namespace }}
spec:
  capacity:
    storage: "{{ .Values.nfsStorage }}"
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.clusterIp }}
    path: "/"
