kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  type: ClusterIP
  clusterIP: {{ .Values.clusterIp }}
  ports:
    - name: nfs
      port: {{ .Values.nfsPort }}
    - name: mountd
      port: {{ .Values.mountdPort }}
    - name: rpcbind
      port: {{ .Values.rpcbindPort }}
  selector:
    role: nfs-server
