apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nfs-pv-provisioning-{{ .Chart.Name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storage }}"