## Append samples you want in your CSV to this file as resources ##
resources:
- daiteap.com_v1alpha1_kubernetescluster.yaml
- daiteap.com_v1alpha1_cloudinstance.yaml
- daiteap.com_v1alpha1_cloudcredential.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
